version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:4.4.8-ubuntu2004
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - type: bind
        source: ./data
        target: /data/db
