version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:4.4.8-ubuntu2004
    command: ["--replSet", "localReplicaSet"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
        - mongodb-data:/data/db
    ports:
     - "27018:27017"

volumes:
    mongodb-data:
        external: false
