version: '3.3'
services:
    service:
        environment:
            - 'OR_DATABASE_CONNECTION_STRING=mongodb://192.168.2.17:27018'
            - 'OR_I_ACCEPT_EULA=true'
        volumes:
            - 'opc-router-OPC-Router-cert:/root/.dotnet/corefx/cryptography/x509stores/'
        image: 'opcrouter/service:4.28'
volumes:
    opc-router-OPC-Router-cert:
        external: false
