version: '3.3'
services:
    service:
        environment:
            - 'OR_DATABASE_CONNECTION_STRING=mongodb://192.168.2.17:27017'
            - 'OR_I_ACCEPT_EULA=true'
        volumes:
            - 'opc-router-OPC-Router-cert:/root/.dotnet/corefx/cryptography/x509stores/'
        image: 'opcrouter/service:4.28-RC'
        command: ["import-project", "--source", "/inrayHackathon.rpe", "--allow-clear-config", "--start-service"]
volumes:
    opc-router-OPC-Router-cert:
        external: false
